apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::888007655814:role/eksctl-eksctl-demo-2-nodegroup-ng-NodeInstanceRole-1G1YS7SHMKZAM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::888007655814:role/UdacityFlaskDeploymentCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-17T04:33:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7035"
  uid: 1be432f4-d78c-4193-bf93-51dfbf7add87
